apiVersion: v1
kind: Service
metadata:
  name: {{ include "meeple.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meeple.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "meeple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
