apiVersion: v1
kind: Service
metadata:
  name: {{ include "meeple.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meeple.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "meeple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
