apiVersion: v1
kind: Service
metadata:
  name: {{ include "meeple.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meeple.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "meeple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
