apiVersion: v1
kind: Service
metadata:
  name: {{ include "meeple.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meeple.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "meeple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
